name: build-test

# on: [push, pull_request]

# Only run on non-draft PRs, and when PRs are synched
on:
  pull_request:
    types: [ready_for_review, synchronize]
      # Don't run if it's just markdown files or doc updates
      paths-ignore:
        - "**.md"
        - "docs/**"
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test in Node
        run: npm run test:node

      - name: Test in Chrome
        run: npm run test:chrome:ci

      - name: Test in Firefox
        run: npm run test:firefox:ci

      - uses: codecov/codecov-action@v1
        with:
          directory: ./coverage
